# Generated by Django 6.0.3 on 2026-03-20 07:35

import django.db.models.deletion
import soyalsite.encrypted_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_code', models.CharField(max_length=32, unique=True)),
                ('status', models.CharField(choices=[('code_pending', 'Kargo kodu bekliyor'), ('code_generated', 'Kargo kodu olusturuldu'), ('shipped', 'Kargoya verildi'), ('delivered', 'Teslim alindi'), ('completed', 'Tamamlandi')], db_index=True, default='code_pending', max_length=20)),
                ('destination_name', models.CharField(blank=True, max_length=120)),
                ('destination_phone_enc', soyalsite.encrypted_fields.EncryptedTextField(blank=True, null=True)),
                ('destination_address_enc', soyalsite.encrypted_fields.EncryptedTextField(blank=True, null=True)),
                ('code_generated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='process', to='applications.listingapplication')),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='processes_d_status_f26fe7_idx')],
            },
        ),
    ]
