# Generated by Django 6.0.3 on 2026-03-20 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('submitted', 'Basvuru Yapildi'), ('pending_selection', 'Secim Bekliyor'), ('selected', 'Aday Secildi'), ('rejected', 'Reddedildi')], db_index=True, default='submitted', max_length=24)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='listings.listing')),
                ('need_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['listing', 'status'], name='application_listing_d292d6_idx'), models.Index(fields=['need_user', 'status'], name='application_need_us_74ee27_idx')],
                'constraints': [models.UniqueConstraint(fields=('listing', 'need_user'), name='unique_application_per_listing_per_user')],
            },
        ),
    ]
