# Generated by Django 6.0.3 on 2026-03-20 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('giysi', 'Giysi'), ('kitap', 'Kitap'), ('elektronik', 'Elektronik'), ('diger', 'Diger')], db_index=True, max_length=32)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField()),
                ('primary_image', models.ImageField(blank=True, null=True, upload_to='listings/images/')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('paused', 'Beklemede'), ('deleted', 'Silindi')], db_index=True, default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['category', 'status'], name='listings_li_categor_8b730f_idx')],
            },
        ),
    ]
